base:
  project: mlops-penguin
  random_state: 42
  target_col: species

data_source:
  s3_source: source_code/penguin_course5i.csv

load_data:
  raw_dataset_csv: data/raw/penguin_course5i.csv

split_data:
  train_path: data/processed/train_penguin_course5i.csv
  test_path: data/processed/test_penguin_course5i.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.7
      l1_ratio: 0.2
      
model_dir: models

reports :
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet_Penguin
  run_name: mlops
  registered_model_name: ElasticNetPenguin
  remote_server_uri: http://127.0.0.1:5000